### ISSUE TITLE
Access fields of an enum variant

### ISSUE THREAD

**Issue by MagicRB** [Diggsey/rust-field-offset#6]
I cannot seem to figure out how to get the offset of fields in a enum variant. I tried `Enum::Variant => field` but that seems to be interfering with the second macro.

**Comment by Diggsey** [comment]
Yeah, this is intentional: this crate provides a safe abstraction for working with "pointer-to-members". It's not possible to provide such an abstraction for enums, because they can have multiple variants, and it's only safe to access fields from the current variant.

**Comment by MagicRB** [comment]
That is most unfortunate, I planned to use this crate to implement custom serialization and deserialization for a protocol struct. I wanted to use bytes and this crate as I need allocation free deserialization, which neither serde or anything else I could find, supports. I know this is off-topic but do you have any suggestions?

**Comment by Diggsey** [comment]
AFAIK, the only way to get a pointer to an enum variant field is to actually have a valid instance of the enum, although you could calculate the offset once and store it for later.

However, I'm not really sure how this helps with serialization/deserialization. Variant pointers won't help you deserialize an enum, because you'd still need to initialise the discriminator somehow, and they won't help serialize an enum, because in that case you have a valid enum to match on so there's no need.

Do you actually mean allocation-free serialization and deserialization? The only way this is possible in general is if you have a fixed message size, otherwise you're going to need *some* form of dynamic allocation. More common is "zero-copy" serialization.

Also, you can achieve both allocation-free and zero-copy serialization with serde: allocation-free is straightforward simply because messages are so limited (no dynamically sized types) that you pretty much get it automatically. Zero-copy requires a bit of effort, but you can use the `bytes` and `string` crates to have any dynamically sized types in your message be backed by the original byte buffer. You don't even need any unsafe code to achieve this.

**Comment by MagicRB** [comment]
Well, what I was trying to do is, rather then having a dynamic Vec or something in my Packet, I put `Bytes` there and when deserializing I wanted to just split the dynamic part from the `BytesMut`, but I need to know the offset of the `Bytes` and other fields as well.

**Comment by Diggsey** [comment]
I'm going to close this as I don't think there's anything this crate can do to help you with that - fundamentally the language has no way to match on an enum without first creating one.
